Dev-depend on browserify-optional
I was getting error `Browserify Error { [Error: Cannot find module 'browserify-optional' from '[redacted]/react-codemirror/node_modules/react-dom-polyfill']`